---
- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
  sudo_user: devleague

- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes
  sudo_user: devleague

- name: restart uber-hackathon 
  command: service "{{ project_name }}" restart
  sudo: yes
  sudo_user: root